# Generated by Django 3.2.8 on 2022-05-24 17:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('social_django', '0010_uid_db_index'),
    ]

    operations = [
        migrations.CreateModel(
            name='GDFile',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('quota', models.PositiveSmallIntegerField(default=0)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='social_django.usersocialauth')),
            ],
            options={
                'db_table': 'gd_files',
            },
        ),
        migrations.CreateModel(
            name='CopyGDFile',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('copy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='copy_copies', to='gdrive.copygdfile')),
                ('original', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='original_copies', to='gdrive.gdfile')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='social_django.usersocialauth')),
            ],
            options={
                'db_table': 'copy_files',
                'ordering': ['-created_date'],
            },
        ),
    ]
